[package]
name = "antar-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../dioxus/packages/dioxus" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-desktop = {path = "../dioxus/packages/desktop" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus-web = { path = "../dioxus/packages/web" }
