[package]
name = "antar-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../dioxus/packages/dioxus" }
dioxus-signals = { path = "../dioxus/packages/signals" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-desktop = {path = "../dioxus/packages/desktop" }
uuid = { version = "1.4.1", features = [ "v4", "fast-rng", "macro-diagnostics" ] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus-web = { path = "../dioxus/packages/web" }
uuid = { version = "1.4.1", features = [ "js", "v4", "fast-rng", "macro-diagnostics" ] }
